### PR TITLE
Closes #36 - "add feature to hide Atom code"

### LINKED ISSUE #36: add feature to hide Atom code
Just like the Hydra feature that exists in the browser, it would be great to be able to toggle the code's visibility when desired with the `CTRL-Shift-H` key binding.

### PR DESCRIPTION
**Pull request by elunaj**
Hi, I'm a big atom-hydra fan, so I took the liberty of implementing this feature request.

It mimics the browser implementation (everything is hidden except hydra visuals). 

Please let me know what you think! :)

### CODE REVIEW

**Review by livacengiz — APPROVED** [review]
thanks @elunaj 🤛

**Comment by kindohm** [comment]
Doing some testing and this is working for me!

**Comment by ojack** [comment]
great!! working on a few other updates and then will update the publically available package :)

**Comment by elunaj** [comment]
Awesome! Glad it's working for everyone. Thanks for merging  :)

**Comment by ojack** [comment]
now its live and should be working!

**Pull request merged**
